version: "3.9"
services:
  challenge:
    build: .
    ports:
      - "4000:4000"
    environment:
      SECRET_KEY_BASE: "Youreally like looking at my secrets, don't you? Have this potion, TRAVELLER"
      PLAYGROUND_ROLE: all
      PHX_HOST: localhost
networks:
  playground:
    name: playground
